
#
# Travis configuration for Firefly III.
#

language: shell
dist: xenial
os: linux

branches:
  only:
  - main

services:
  - docker

jobs:
  include:
    - dist: xenial
      arch: amd64
      env: ARCH=amd64 VERSION=5.4.1
      stage: build
      script: ./travis.sh
    - dist: xenial
      arch: amd64
      env: ARCH=arm VERSION=5.4.1
      stage: build
      script: ./travis.sh
    - dist: xenial
      arch: arm64
      env: ARCH=arm64 VERSION=5.4.1
      stage: build
      script: ./travis.sh
    - dist: xenial
      arch: amd64
      env:  VERSION=5.4.1
      stage: manifest
      script: ./manifest.sh
