language: shell
dist: xenial
os: linux

branches:
  only:
  - master

services:
  - docker

#
# Job configuration:
# - ARCH    = The architecture of the build. This should match the "arch:"" argument of the build itself.
# - VERSION = Either the version to build OR "develop" to build the latest develop version.

jobs:
  include:
    - dist: xenial
      os: linux
      arch: amd64
      env: ARCH=amd64 VERSION=5.2.0-beta.1
      stage: build
      script: ./scripts/travis.sh
    - dist: xenial
      os: linux
      arch: amd64
      env: ARCH=arm VERSION=5.2.0-beta.1
      stage: build
      script: ./scripts/travis.sh
    - dist: xenial
      os: linux
      arch: arm64
      env: ARCH=arm64 VERSION=5.2.0-beta.1
      stage: build
      script: ./scripts/travis.sh
    - dist: xenial
      os: linux
      arch: amd64
      env: VERSION=5.2.0-beta.1
      stage: manifest
      script: ./scripts/manifest.sh
