language: shell
dist: xenial
os: linux

# safelist
branches:
  only:
  - master

services:
  - docker

jobs:
  include:
    - dist: xenial
      os: linux
      arch: amd64
      env: VERSION_ONLY=false ARCH=amd64 CHANNEL=alpha VERSION=5.2.0-alpha.1 RELEASE=develop
      stage: build
      script: ./scripts/travis.sh
    - dist: xenial
      os: linux
      arch: amd64
      env: VERSION_ONLY=false ARCH=arm CHANNEL=alpha VERSION=5.2.0-alpha.1 RELEASE=develop
      stage: build
      script: ./scripts/travis.sh
    - dist: xenial
      os: linux
      arch: arm64
      env: VERSION_ONLY=false ARCH=arm64 CHANNEL=alpha VERSION=5.2.0-alpha.1 RELEASE=develop
      stage: build
      script: ./scripts/travis.sh
    - dist: xenial
      os: linux
      arch: amd64
      env: VERSION_ONLY=false CHANNEL=alpha VERSION=5.2.0-alpha.1 RELEASE=develop
      stage: manifest
      script: ./scripts/manifest.sh
