
#
# Travis configuration for Firefly III.
#

language: shell
dist: xenial
os: linux

branches:
  only:
  - main

services:
  - docker

jobs:
  include:
    - dist: xenial
      arch: amd64
      env: ARCH=amd64 VERSION=develop
      stage: build
      script: ./travis.sh
    - dist: xenial
      arch: amd64
      env: ARCH=arm32v7 VERSION=develop
      stage: build
      script: ./travis.sh
    - dist: xenial
      arch: arm64
      env: ARCH=arm64 VERSION=develop
      stage: build
      script: ./travis.sh
    - dist: xenial
      arch: amd64
      env:  VERSION=develop
      stage: manifest
      script: ./manifest.sh
